### ISSUE TITLE
DBUS error after installing dependencies

### ISSUE THREAD

**Issue by dino213dz** [x899/chrome_password_grabber#19]
Hi  all!

I have an issue after the installation of dependencies :
- SecretStorage==3.3.0
- pycrypto=2.6.1 ) then running

The error concern the env var called **DBUS_SESSION_BUS_ADDRESS** 

I tried without SUDO:

_Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/secretstorage/__init__.py", line 72, in dbus_init
    connection = open_dbus_connection()
  File "/usr/lib/python3/dist-packages/jeepney/io/blocking.py", line 255, in open_dbus_connection
    conn = DBusConnection(sock)
  File "/usr/lib/python3/dist-packages/jeepney/io/blocking.py", line 68, in __init__
    hello_reply = self.bus_proxy.Hello()
  File "/usr/lib/python3/dist-packages/jeepney/io/blocking.py", line 223, in inner
    return self._connection.send_and_get_reply(
  File "/usr/lib/python3/dist-packages/jeepney/io/blocking.py", line 134, in send_and_get_reply
    self.send_message(message, serial=serial)
  File "/usr/lib/python3/dist-packages/jeepney/io/blocking.py", line 83, in send
    self.sock.sendall(data)
BrokenPipeError: [Errno 32] Broken pipe

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/scripts/chrome_password_grabber/./decrypt_chrome_pass_ulti.py", line 2, in <module>
    chrome_pwd = Chrome()
  File "/scripts/chrome_password_grabber/chrome.py", line 113, in __init__
    self.chrome_os = ChromeLinux()
  File "/scripts/chrome_password_grabber/chrome.py", line 79, in __init__
    bus = secretstorage.dbus_init()
  File "/usr/lib/python3/dist-packages/secretstorage/__init__.py", line 80, in dbus_init
    raise SecretServiceNotAvailableException(str(ex)) from ex
secretstorage.exceptions.SecretServiceNotAvailableException: [Errno 32] Broken pipe_

Then I tried wiith SUDO:

_sudo python3 ./decrypt_chrome_pass_ulti.py 
sudo: impossible de résoudre l'hôte Parrot: Nom ou service inconnu
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/secretstorage/__init__.py", line 72, in dbus_init
    connection = open_dbus_connection()
  File "/usr/lib/python3/dist-packages/jeepney/io/blocking.py", line 243, in open_dbus_connection
    bus_addr = get_bus(bus)
  File "/usr/lib/python3/dist-packages/jeepney/bus.py", line 53, in get_bus
    return find_session_bus()
  File "/usr/lib/python3/dist-packages/jeepney/bus.py", line 42, in find_session_bus
    addr = os.environ['DBUS_SESSION_BUS_ADDRESS']
  File "/usr/lib/python3.9/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'DBUS_SESSION_BUS_ADDRESS'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/scripts/chrome_password_grabber/./decrypt_chrome_pass_ulti.py", line 2, in <module>
    chrome_pwd = Chrome()
  File "/scripts/chrome_password_grabber/chrome.py", line 113, in __init__
    self.chrome_os = ChromeLinux()
  File "/scripts/chrome_password_grabber/chrome.py", line 79, in __init__
    bus = secretstorage.dbus_init()
  File "/usr/lib/python3/dist-packages/secretstorage/__init__.py", line 78, in dbus_init
    raise SecretServiceNotAvailableException(reason) from ex
secretstorage.exceptions.SecretServiceNotAvailableException: Environment variable DBUS_SESSION_BUS_ADDRESS is unset_

**Comment by dino213dz** [comment]
List of installed packages :
at-spi2-core/rolling,now 2.38.0-2 amd64  
bamfdaemon/rolling,now 0.5.4-2 amd64  
colord/rolling,now 1.4.5-3 amd64  
dbus/rolling,now 1.12.20-2 amd64  
dbus-user-session/rolling,now 1.12.20-2 amd64  
dbus-x11/rolling,now 1.12.20-2 amd64  
gir1.2-bamf-3/rolling,now 0.5.4-2 amd64  
gir1.2-packagekitglib-1.0/rolling,now 1.2.2-2 amd64  
gir1.2-secret-1/rolling,now 0.20.4-2 amd64  
libbamf3-2/rolling,now 0.5.4-2 amd64  
libdbus-1-3/rolling,now 1.12.20-2 amd64  
libdbus-1-dev/rolling,now 1.12.20-2 amd64  
libdbus-glib-1-2/rolling,now 0.110-6 amd64  
libdbusmenu-glib4/rolling,now 18.10.20180917~bzr492+repack1-2 amd64  
libdbusmenu-gtk3-4/rolling,now 18.10.20180917~bzr492+repack1-2 amd64  
libmm-glib0/rolling,now 1.14.12-0.1 amd64  
libnet-dbus-perl/rolling,now 1.2.0-1+b1 amd64  
libpackagekit-glib2-18/rolling,now 1.2.2-2 amd64  
libqt5dbus5/rolling,now 5.15.2+dfsg-5 amd64  
libsecret-1-0/rolling,now 0.20.4-2 amd64  
libsecret-common/rolling,now 0.20.4-2 all  
modemmanager/rolling,now 1.14.12-0.1 amd64  
packagekit/rolling,now 1.2.2-2 amd64  
packagekit-tools/rolling,now 1.2.2-2 amd64  
padbuster/rolling,now 0.3.3-1kali3 all  
python3-dbus/rolling,now 1.2.16-5 amd64  
python3-jeepney/rolling,now 0.6.0-1 all  
python3-pyqt5/rolling,now 5.15.2+dfsg-3 amd64  
qtbase5-dev-tools/rolling,now 5.15.2+dfsg-5 amd64  
ruby-dbus/rolling,now 0.16.0-1 all  
xdg-dbus-proxy/rolling,now 0.1.2-2 amd64

**Comment by dino213dz** [comment]
┌─[✗]─[root@Parrot]─[/scripts/chrome_password_grabber]
└──╼ #service dbus status
● dbus.service - D-Bus System Message Bus
     Loaded: loaded (/lib/systemd/system/dbus.service; static)
     Active: active (running) since Mon 2021-06-07 10:32:43 CEST; 2 weeks 0 days ago
TriggeredBy: ● dbus.socket
       Docs: man:dbus-daemon(1)
   Main PID: 544 (dbus-daemon)
      Tasks: 1 (limit: 7031)
     Memory: 2.9M
        CPU: 17.235s
     CGroup: /system.slice/dbus.service
             └─544 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only

juin 21 20:03:48 Parrot dbus-daemon[544]: [system] Activating via systemd: service name='org.freedesktop.nm_dispatcher' unit='dbus-org.freedesktop.nm-dispatcher.service' requested by ':1.7'>
juin 21 20:03:48 Parrot dbus-daemon[544]: [system] Successfully activated service 'org.freedesktop.nm_dispatcher'
juin 21 20:04:26 Parrot dbus-daemon[544]: [system] Activating via systemd: service name='org.freedesktop.nm_dispatcher' unit='dbus-org.freedesktop.nm-dispatcher.service' requested by ':1.7'>
juin 21 20:04:26 Parrot dbus-daemon[544]: [system] Successfully activated service 'org.freedesktop.nm_dispatcher'
juin 21 20:04:26 Parrot dbus-daemon[544]: [system] Activating via systemd: service name='org.freedesktop.hostname1' unit='dbus-org.freedesktop.hostname1.service' requested by ':1.1049' (uid>
juin 21 20:04:26 Parrot dbus-daemon[544]: [system] Successfully activated service 'org.freedesktop.hostname1'
juin 21 20:04:26 Parrot dbus-daemon[544]: [system] Activating via systemd: service name='org.freedesktop.resolve1' unit='dbus-org.freedesktop.resolve1.service' requested by ':1.1049' (uid=0>
juin 21 20:04:26 Parrot dbus-daemon[544]: [system] Activation via systemd failed for unit 'dbus-org.freedesktop.resolve1.service': Unit dbus-org.freedesktop.resolve1.service not found.
juin 21 20:16:30 Parrot dbus-daemon[544]: [system] Activating via systemd: service name='org.freedesktop.PackageKit' unit='packagekit.service' requested by ':1.8259' (uid=0 pid=163857 comm=>
juin 21 20:16:30 Parrot dbus-daemon[544]: [system] Successfully activated service 'org.freedesktop.PackageKit'
