### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x86 in position 0: invalid start byte

### ISSUE THREAD

**Issue by LarryBug** [x899/chrome_password_grabber#25]
larry@LarryDeMBP chrome_password_grabber-master % python chrome.py

/Users/larry/Library/Application Support/Google/Chrome/Default/
Traceback (most recent call last):
  File "/Users/larry/Downloads/chrome_password_grabber-master/chrome.py", line 158, in <module>
    main()
  File "/Users/larry/Downloads/chrome_password_grabber-master/chrome.py", line 154, in main
    chrome_pwd.get_password(prettyprint=True)
  File "/Users/larry/Downloads/chrome_password_grabber-master/chrome.py", line 134, in get_password
    _passwd = self.chrome_os.decrypt_func(result[2])
  File "/Users/larry/Downloads/chrome_password_grabber-master/chrome.py", line 50, in decrypt_func
    return decrypted.strip().decode('utf8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x86 in position 0: invalid start byte
----
even I configured utf8 still get this error....but I checked the code line #50, it has utf8, why still has this error??

**Comment by LarryBug** [comment]
change line #50 to 
return decrypted.strip().decode('utf8',"ignore")
